### PR TITLE
gtest for bcast

### PR DESCRIPTION
**Pull request by lukasdreyer**
**_Describe your changes here:_**
Rewrite the unit test for bcast in the googletest Framework. Use a parameterized testsuite to create instances of the test for each eclass. Thus, if only one eclass fails, one gets explicit output, for which of the cases the test failed.

Remove the corresponding old unit test.

Additionally, the eclass test was already ported and extended in gtest in the initial merge, so I removed the old eclass test here as well.

**_All these boxes must be checked by the reviewers before merging the pull request:_**

- [x] The author added a BSD statement to `doc/` (or already has one)
- [x] The code compiles without warning in debugging and release mode, with and without MPI (this should be executed automatically in a github action)

  If the Pull request indroduces code that is not covered by the github action (for example coupling with a new library):
  - [ ] Should this use case be added to the github action?
  - [ ] If not, does the specific use case compile and all tests pass (check manually)

- [x] All tests pass (in various configurations, this should be executed automatically in a github action)
- [x] New source/header files are properly added to the Makefiles
- [x] The reviewer executed the new code features at least once and checked the results manually
- [x] The code is covered in an existing or new test case
- [x] The code follows the [t8code coding guidelines](https://github.com/holke/t8code/wiki/Coding-Guideline)
- [ ] The code is well documented
- [x] All function declarations, structs/classes and their members have a proper doxygen documentation
- [x] All new algorithms and data structures are sufficiently optimal in terms of memory and runtime (If this should be merged, but there is still potential for optimization, create a new issue)
- [x] Testing of this template: If you feel something is missing from this list, contact the developers

### CODE REVIEW

**Review by Davknapp — CHANGES_REQUESTED** [review]
The code itself is very nice! Please add some comments to the bcast test concerning its functionality.

**Comment by lukasdreyer** [comment]
The check seems to not be running again and I can't figure out how to start it manually.

**Comment by holke** [comment]
> The check seems to not be running again and I can't figure out how to start it manually.

You mean the github action check?
It should start after each push to this PR.

You can also run it manually on this branch (but will not be shown in this PR), by going to actions -> t8code tests -> Run workflow -> Choose this branch

**Comment by lukasdreyer** [comment]
> You mean the github action check? It should start after each push to this PR.
> 
> You can also run it manually on this branch (but will not be shown in this PR), by going to actions -> t8code tests -> Run workflow -> Choose this branch

Yes, I mean the github action check. After my last push, it seems that it was not triggered, as it shows:

> Some checks haven’t completed yet
> 1 expected check
> build: Expected — Waiting for status to be reported
and I expected it to run automatically or that there is an option to trigger it manually in the PR.

**Comment by holke** [comment]
> > You mean the github action check? It should start after each push to this PR.
> > You can also run it manually on this branch (but will not be shown in this PR), by going to actions -> t8code tests -> Run workflow -> Choose this branch
> 
> Yes, I mean the github action check. After my last push, it seems that it was not triggered, as it shows:
> 
> > Some checks haven’t completed yet
> > 1 expected check
> > build: Expected — Waiting for status to be reported
> > and I expected it to run automatically or that there is an option to trigger it manually in the PR.

mhmm...looks like its scheduled but doesnt start. Idk why its not running.

**Review by Davknapp — APPROVED** [review]

**Pull request merged**
