### PR TITLE
increase version number in tests

### PR DESCRIPTION
**Pull request by holke**
**_Describe your changes here:_**

Increased in the version number to 0.91.0 in preparation of release.
This should be merged before #287 

**_All these boxes must be checked by the reviewers before merging the pull request:_**

As a reviewer please read through all the code lines and make sure that the code is fully understood, bug free, well-documented and well-structured.

- [x] The author added a BSD statement to `doc/` (or already has one)
- [x] The code compiles without warning in debugging and release mode, with and without MPI (this should be executed automatically in a github action)

  If the Pull request indroduces code that is not covered by the github action (for example coupling with a new library):
  - [ ] Should this use case be added to the github action?
  - [ ] If not, does the specific use case compile and all tests pass (check manually)

- [ ] All tests pass (in various configurations, this should be executed automatically in a github action)
- [x] New source/header files are properly added to the Makefiles
- [x] The reviewer executed the new code features at least once and checked the results manually
- [x] The code is covered in an existing or new test case
- [x] The code follows the [t8code coding guidelines](https://github.com/holke/t8code/wiki/Coding-Guideline)
- [x] The code is well documented
- [x] All function declarations, structs/classes and their members have a proper doxygen documentation
- [x] All new algorithms and data structures are sufficiently optimal in terms of memory and runtime (If this should be merged, but there is still potential for optimization, create a new issue)
- [x] Testing of this template: If you feel something is missing from this list, contact the developers

### CODE REVIEW

**Review by sandro-elsweijer — COMMENTED** [review]
0.9.0 to 0.91.0 is a very big step. Did you mean 0.10.0 or maybe 0.9.1?

**Comment by holke** [comment]
> 0.9.0 to 0.91.0 is a very big step. Did you mean 0.10.0 or maybe 0.9.1?

Changed to 0.10.0

**Comment by sandro-elsweijer** [comment]
The gtest for the minor version seems to need an edit too

**Comment by holke** [comment]
i forgot to delete the v0.91.0 tag remotely. Only deleted it locally, which resulted in the version still being 0.91.0 and the test failing.

**Comment by holke** [comment]
and the 0.10.0 tag was on the wrong commit.

Corrected it, now it should finally work.

**Pull request merged**
