### PR TITLE
Feature version handling

### PR DESCRIPTION
**Pull request by holke**
**_Describe your changes here:_**

Added version handling to t8code.

- New functions to get the version string, the major, minor, and patch version
- New tests for these functions
- An example that prints the version number

Is ready for review, but should not be merged yet.

**_All these boxes must be checked by the reviewers before merging the pull request:_**

- [x] The author added a BSD statement to `doc/` (or already has one)
- [x] The code compiles without warning in debugging and release mode, with and without MPI (this should be executed automatically in a github action)

  If the Pull request indroduces code that is not covered by the github action (for example coupling with a new library):
  - [ ] Should this use case be added to the github action?
  - [ ] If not, does the specific use case compile and all tests pass (check manually)

- [x] All tests pass (in various configurations, this should be executed automatically in a github action)
- [x] New source/header files are properly added to the Makefiles
- [x] The reviewer executed the new code features at least once and checked the results manually
- [x] The code is covered in an existing or new test case
- [x] The code follows the [t8code coding guidelines](https://github.com/holke/t8code/wiki/Coding-Guideline)
- [x] The code is well documented
- [x] All function declarations, structs/classes and their members have a proper doxygen documentation
- [x] All new algorithms and data structures are sufficiently optimal in terms of memory and runtime (If this should be merged, but there is still potential for optimization, create a new issue)
- [ ] Testing of this template: If you feel something is missing from this list, contact the developers

### CODE REVIEW

**Review by Davknapp — APPROVED** [review]
Nice feature! 
We should check for further basic-assumptions and add them to the gtest-basic test!

**Comment by holke** [comment]
Taken this out of WIP.
Can we merge this?

**Comment by Davknapp** [comment]
> Taken this out of WIP. Can we merge this?

Yes, but there is a merge-conflict that should be solved before

**Comment by holke** [comment]
Fixed the conflicts. We can merge when the tests pass.

**Pull request merged**
