### PR TITLE
Introduce new directory structure for examples

### PR DESCRIPTION
**Pull request by lukasdreyer**
**_Describe your changes here:_**
Split up the example directory into the 3 directories `benchmarks, tutorials, examples`

**_All these boxes must be checked by the reviewers before merging the pull request:_**

- [x] The author added a BSD statement to `doc/` (or already has one)
- [x] The code compiles without warning in debugging and release mode, with and without MPI (this should be executed automatically in a github action)

  If the Pull request indroduces code that is not covered by the github action (for example coupling with a new library):
  - [ ] Should this use case be added to the github action?
  - [ ] If not, does the specific use case compile and all tests pass (check manually)

- [x] All tests pass (in various configurations, this should be executed automatically in a github action)
- [x] New source/header files are properly added to the Makefiles
- [x] The reviewer executed the new code features at least once and checked the results manually
- [ ] The code is covered in an existing or new test case
- [x] The code follows the [t8code coding guidelines](https://github.com/holke/t8code/wiki/Coding-Guideline)
- [x] The code is well documented
- [ ] All function declarations, structs/classes and their members have a proper doxygen documentation
- [ ] All new algorithms and data structures are sufficiently optimal in terms of memory and runtime (If this should be merged, but there is still potential for optimization, create a new issue)
- [ ] Testing of this template: If you feel something is missing from this list, contact the developers

### CODE REVIEW

**Review by Davknapp — CHANGES_REQUESTED** [review]
It looks good so far. but the example
`example/IO/cmesh/gmsh/t8_load_and_refine_square_w_hole` does not find its input data anymore. Please add the data and update the relative path in the example.

**Comment by lukasdreyer** [comment]
> It looks good so far. but the example `example/IO/cmesh/gmsh/t8_load_and_refine_square_w_hole` does not find its input data anymore. Please add the data and update the relative path in the example.

Apparently, it did not find its input data before as well. I am currently trying to figure out, what this line in the Makefile is doing:
```
dist_t8data_DATA += \
  example/IO/cmesh/gmsh/circlesquare_hybrid_hole.msh
```
It appeared in the old Makefile and I thought it was responsible for copying data into the build directory. If this is the case, it does not seem to be functioning anymore.

**Comment by lukasdreyer** [comment]
With these last commits, the gmsh example should be working again. The triangle and tetgen examples on the other hand get a corresponding file prefix as an argument. We currently do not give any example files for these possibilities to create a cmesh.

**Comment by Davknapp** [comment]
> With these last commits, the gmsh example should be working again. The triangle and tetgen examples on the other hand get a corresponding file prefix as an argument. We currently do not give any example files for these possibilities to create a cmesh.

Unfortunatly the example does not work, but the root of the problem does not lay in this PR. I opened Issue #275 to fix it.

**Review by Davknapp — APPROVED** [review]

**Pull request merged**
